name = "kss1st"
compatibility_date = "2024-01-29"
compatibility_flags = ["nodejs_compat"]

# 빌드 관련 모든 설정을 이 섹션으로 그룹화합니다.
[pages_build]
command = "npm install"
build_output_dir = "." # 빌드 결과물 디렉토리도 여기서 지정합니다.

[[kv_namespaces]]
binding = "KSS1ST_STATUS"
id = "36130b05b81347a49c66133880479b16"
preview_id = "36130b05b81347a49c66133880479b16"
