name = "kss1st"
compatibility_date = "2024-01-29"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages가 요구하는 필수 최상위 속성
pages_build_output_dir = "."

# 빌드(조립) 방법을 지시하는 섹션
[pages_build]
command = "npm install"

[[kv_namespaces]]
binding = "KSS1ST_STATUS"
id = "36130b05b81347a49c66133880479b16"
preview_id = "36130b05b81347a49c66133880479b16"
