# wrangler.toml - 최종 진짜 수정안
name = "kss1st"
compatibility_date = "2024-01-29"
compatibility_flags = ["nodejs_compat"]

# 완성품은 반드시 'public' 폴더에 두겠다고 명시합니다.
pages_build_output_dir = "public"

[[kv_namespaces]]
binding = "KSS1ST_STATUS"
id = "4c0f15cec2c641fdbbe68f04ab45446f"
preview_id = "4c0f15cec2c641fdbbe68f04ab45446f"