name = "kss1st"
compatibility_date = "2024-01-29"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "public"

[[kv_namespaces]]
binding = "KSS1ST_STATUS"
id = "4c0f15cec2c641fdbbe68f04ab45446f"
preview_id = "4c0f15cec2c641fdbbe68f04ab45446f"
